### PR TITLE
work background 

### PR DESCRIPTION
**Pull request by pav-tmn**
like that the application can run in the background, it is possible to do this?

### CODE REVIEW

**Comment by Paku-** [comment]
I'm not sure if you wanted to merge 160 commits ?? Where is the true code change ?

**Comment by pav-tmn** [comment]
I do not have the skills. I said maybe you implement it in the new version

**Comment by Paku-** [comment]
But you issued a new pull request with 160 changes in the code! Was it a mistake ?

**Comment by pav-tmn** [comment]
yes

**Comment by Paku-** [comment]
ok ... so will have to clean this pull request ... but my answer to your question is that code is dead now as I do not have time to work on it anymore. If you know someone who would like to work on it, I can help a little.

**Comment by pav-tmn** [comment]
but I have the time and one which will be able to do this, write to the address mail for communication

**Comment by Paku-** [comment]
So just make changes and send next, proper this time, pull request. I will review it and merge it.

**Pull request closed without merging**
